// Regenerates netlify/functions/seed-content.js from src/lib/defaultContent.js
// Run with: node scripts/generate-seed.mjs
//
// NOTE: this is written as a real .js ES module (export default {...}), not a
// .json file read at runtime with fs.readFileSync. Netlify's function bundler
// (zip-it-and-ship-it) determines which files to include in a deployed
// function by statically analyzing import/require statements — a runtime
// fs.readFileSync call on a computed path can't be traced, so a plain .json
// file loaded that way can silently get left out of the deployed bundle,
// crashing the function in production. A static `import` is always detected
// and bundled correctly.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { DEFAULT_CONTENT } from "../src/lib/defaultContent.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(__dirname, "../netlify/functions/seed-content.js");
const body = "// AUTO-GENERATED by scripts/generate-seed.mjs — do not edit by hand.\nexport default " + JSON.stringify(DEFAULT_CONTENT, null, 2) + ";\n";
writeFileSync(outPath, body);
console.log("Wrote", outPath);
